import type { TriageBoardData, TriageReviewer, TriageReviewerPopover } from './types';
import { cardsForView } from './triageViews';

const fictionalAvatars = {
  amara: '/redesign/triage-amara-okafor.jpg',
  aarav: '/redesign/triage-aarav-mehta.jpg',
  casey: '/redesign/triage-casey-reed.jpg',
  mateo: '/redesign/slack-mara-chen.jpg',
  nadia: '/redesign/slack-priya-shah.jpg',
  kwame: '/redesign/slack-theo-martin.jpg',
} as const;

export const reviewerProfiles = {
  amara: {
    id: 'amara-okafor',
    name: 'Amara Okafor',
    handle: '@amaraokafor',
    slackHandle: '@amara',
    avatar: fictionalAvatars.amara,
  },
  aarav: {
    id: 'aarav-mehta',
    name: 'Aarav Mehta',
    handle: '@aaravmehta',
    slackHandle: '@aarav',
    avatar: fictionalAvatars.aarav,
  },
  casey: {
    id: 'casey-reed',
    name: 'Casey Reed',
    handle: '@caseyreed',
    slackHandle: '@casey',
    avatar: fictionalAvatars.casey,
  },
  mateo: {
    id: 'mateo-silva',
    name: 'Mateo Silva',
    handle: '@mateosilva',
    slackHandle: '@mateo',
    avatar: fictionalAvatars.mateo,
  },
  nadia: {
    id: 'nadia-petrova',
    name: 'Nadia Petrova',
    handle: '@nadiapetrova',
    slackHandle: '@nadia',
    avatar: fictionalAvatars.nadia,
  },
  kwame: {
    id: 'kwame-mensah',
    name: 'Kwame Mensah',
    handle: '@kwamemensah',
    slackHandle: '@kwame',
    avatar: fictionalAvatars.kwame,
  },
} satisfies Record<string, TriageReviewer>;

const reviewerScenarios = {
  assignedPair: {
    reviewers: [{ ...reviewerProfiles.amara, selected: true }, { ...reviewerProfiles.casey }],
    suggestions: [
      {
        reviewer: reviewerProfiles.mateo,
      },
    ],
  },
  suggestedCandidate: {
    reviewers: [{ ...reviewerProfiles.kwame }, { ...reviewerProfiles.casey }, { ...reviewerProfiles.mateo }],
    suggestions: [
      {
        reviewer: reviewerProfiles.amara,
      },
    ],
  },
  teamReview: {
    reviewers: [
      { ...reviewerProfiles.aarav, selected: true },
      { ...reviewerProfiles.nadia },
      { ...reviewerProfiles.mateo },
    ],
  },
  soloReviewer: {
    reviewers: [{ ...reviewerProfiles.nadia, selected: true }],
  },
  noReviewer: {
    reviewers: [],
    emptyMessage: 'No reviewers assigned.',
    suggestions: [
      {
        reviewer: reviewerProfiles.casey,
      },
    ],
  },
  noReviewerMultiple: {
    reviewers: [],
    emptyMessage: 'No reviewers assigned.',
    suggestions: [
      {
        reviewer: reviewerProfiles.casey,
      },
      {
        reviewer: reviewerProfiles.kwame,
      },
    ],
  },
} satisfies Record<string, TriageReviewerPopover>;

/**
 * Triage board content adapted from the Figma source of truth (July Homepage
 * - New Cut, node 299:23275). Card titles use fictional, product-neutral
 * examples. Exact synthetic recency, activity dates, and match percentages are
 * omitted; visible counts are derived from the sample cards.
 *
 * The board groups by priority, so the design's priority groups are the columns,
 * carried onto the documented P0–P3 scale. Each card's priority pill matches its column.
 */
const baseTriageBoard: TriageBoardData = {
  searchPlaceholder: 'Search pull requests',
  viewGroups: [
    {
      id: 'pull-requests',
      label: 'Pull requests',
      views: [
        { id: 'all-reviews-view', label: 'All reviews', count: '', active: true },
        { id: 'needs-my-review-view', label: 'Needs my review', count: '' },
        { id: 'authored-by-me-view', label: 'Authored by me', count: '' },
        { id: 'safe-to-merge-view', label: 'Safe to merge', count: '' },
      ],
    },
    {
      id: 'saved-views',
      label: 'Saved views',
      views: [
        { id: 'security-watch-view', label: 'Security watch', count: '' },
        { id: 'release-train-view', label: 'Release train', count: '' },
        { id: 'agent-created-view', label: 'Agent-created PRs', count: '' },
      ],
    },
  ],
  columns: [
    { id: 'p0', title: 'P0', count: '' },
    { id: 'p1', title: 'P1', count: '' },
    { id: 'p2', title: 'P2', count: '' },
    { id: 'p3', title: 'P3', count: '' },
  ],
  cards: [
    {
      id: 'p1-1',
      columnId: 'p0',
      repository: 'identity-platform',
      reference: '#25493',
      title: 'fix(auth): rotate exposed production signing key',
      reason: 'Agent detected a compromised key path. Human judgment required.',
      priority: 'P0',
      tags: ['Agent-created', 'Needs human review', 'High risk', 'Deep review', 'High blast radius'],
      stack: 'Change Stack',
      author: '@sentinel-agent[bot]',
      reviewerPopover: reviewerScenarios.assignedPair,
      avatars: [fictionalAvatars.amara, fictionalAvatars.casey],
    },
    {
      id: 'p1-2',
      columnId: 'p0',
      repository: 'platform',
      reference: '#25095',
      title: 'feat(mcp): add integrations-authoritative reverse tunnel routing',
      reason: 'New, active work needs your attention.',
      priority: 'P0',
      tags: ['Needs human review', 'High risk', 'Deep review', 'High complexity', 'High effort'],
      stack: 'Change Stack',
      author: '@caseyreed (Casey Reed)',
      overflow: '+2',
      reviewerPopover: reviewerScenarios.assignedPair,
      avatars: [fictionalAvatars.aarav, fictionalAvatars.kwame, fictionalAvatars.mateo],
    },
    {
      id: 'p1-3',
      columnId: 'p0',
      repository: 'webapp',
      reference: '#2704',
      title: 'docs(blog): explain graph engineering and LLM orchestration',
      reason: 'This may need maintainer follow-up.',
      priority: 'P0',
      tags: ['Needs human review', 'Low risk', 'Review later', 'Medium complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@aaravmehta (Aarav Mehta)',
      reviewerPopover: reviewerScenarios.noReviewerMultiple,
    },
    {
      id: 'p1-4',
      columnId: 'p0',
      repository: 'design-system',
      reference: '#736',
      title: 'fix(ads): separate campaign asset upload authorization',
      reason: 'Review has been waiting and may need coordination.',
      priority: 'P0',
      tags: ['Needs human review', 'Low risk', 'Deep review', 'High complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@amaraokafor (Amara Okafor)',
      reviewerPopover: reviewerScenarios.soloReviewer,
      avatars: [fictionalAvatars.casey],
    },
    {
      id: 'p1-5',
      columnId: 'p0',
      repository: 'design-system',
      reference: '#718',
      title: 'feat(ads): automate campaign configuration',
      reason: 'Review has been waiting and may need coordination.',
      priority: 'P0',
      tags: ['Needs human review', 'Low risk', 'Quick review', 'High complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@amaraokafor (Amara Okafor)',
      reviewerPopover: reviewerScenarios.soloReviewer,
      avatars: [fictionalAvatars.nadia],
    },
    {
      id: 'p1-6',
      columnId: 'p0',
      repository: 'design-system',
      reference: '#548',
      title: 'docs(ads): separate brand and non-brand campaign handling',
      reason: 'This may need maintainer follow-up.',
      priority: 'P0',
      tags: ['Needs author action', 'Low risk', 'Quick review', 'Low complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@sofiaalvarez (Sofia Alvarez)',
    },
    {
      id: 'p1-7',
      columnId: 'p0',
      repository: 'design-system',
      reference: '#470',
      title: 'feat(experiments): TTS brand-voice bake-off — corpus, rubric, matrix, key-optional harness',
      reason: 'This may need maintainer follow-up.',
      priority: 'P0',
      tags: ['Needs author action', 'Low risk', 'Quick review', 'Medium complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@aaravmehta (Aarav Mehta)',
    },
    {
      id: 'p1-8',
      columnId: 'p0',
      repository: 'design-system',
      reference: '#592',
      title: 'feat(skills): add manual large-change handoff',
      reason: 'This may need maintainer follow-up.',
      priority: 'P0',
      tags: ['Needs author action', 'Low risk', 'Quick review', 'Low complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@aaravmehta (Aarav Mehta)',
    },
    {
      id: 'p1-9',
      columnId: 'p0',
      repository: 'platform',
      reference: '#25473',
      title: 'fix(reviews): stop reporting a successful reviewer request as a failure',
      reason: 'New, active work needs your attention.',
      priority: 'P0',
      tags: [
        'Bugfix',
        'Low risk',
        'Standard review',
        'High blast radius',
        'High complexity',
        'Medium effort',
        'Issue severity: Medium',
      ],
      stack: 'Change Stack',
      author: '@kenjisato (Kenji Sato)',
      overflow: '+4',
      reviewerPopover: reviewerScenarios.suggestedCandidate,
      avatars: [fictionalAvatars.mateo, fictionalAvatars.nadia, fictionalAvatars.kwame],
    },
    {
      id: 'p1-10',
      columnId: 'p0',
      repository: 'platform',
      reference: '#25479',
      title: 'fix(analytics): attribute frontend events from the server-side locator',
      reason: 'New, active work needs your attention.',
      priority: 'P0',
      tags: ['Low risk', 'Standard review', 'High complexity', 'Medium effort'],
      stack: 'Change Stack',
      author: '@kenjisato (Kenji Sato)',
      overflow: '+3',
      reviewerPopover: reviewerScenarios.teamReview,
      avatars: [fictionalAvatars.kwame, fictionalAvatars.amara, fictionalAvatars.aarav],
    },
    {
      id: 'p1-11',
      columnId: 'p0',
      repository: 'platform',
      reference: '#25467',
      title: 'fix(triage): exclude authored PRs from the review queue',
      reason: 'New, active work needs your attention.',
      priority: 'P0',
      tags: [
        'Bugfix',
        'Low risk',
        'Quick review',
        'High blast radius',
        'Medium complexity',
        'Low effort',
        'Issue severity: Medium',
      ],
      stack: 'Change Stack',
      author: '@laylahaddad (Layla Haddad)',
      overflow: '+1',
      reviewerPopover: reviewerScenarios.assignedPair,
      avatars: [fictionalAvatars.casey, fictionalAvatars.mateo, fictionalAvatars.nadia],
    },
    {
      id: 'p2-12',
      columnId: 'p1',
      repository: 'events',
      reference: '#63',
      title: 'feat(managed-events): own historical event programs',
      reason: 'Assign a reviewer to keep this moving.',
      priority: 'P1',
      tags: [
        'New changes since last review',
        'Needs human review',
        'Low risk',
        'Deep review',
        'High complexity',
        'Low effort',
      ],
      stack: 'Change Stack',
      author: '@aaravmehta (Aarav Mehta)',
      reviewerPopover: reviewerScenarios.noReviewer,
    },
    {
      id: 'p2-14',
      columnId: 'p1',
      repository: 'carrot-ui',
      reference: '#126',
      title: 'feat(theme): tasteful depth, applied across the system',
      reason: 'Review has been waiting and may need coordination.',
      priority: 'P1',
      tags: ['New changes since last review', 'Needs human review', 'Low risk', 'Review later', 'Low effort'],
      stack: 'Change Stack',
      author: '@nadiapetrova (Nadia Petrova)',
      overflow: '+2',
      reviewerPopover: reviewerScenarios.suggestedCandidate,
      avatars: [fictionalAvatars.nadia, fictionalAvatars.casey, fictionalAvatars.mateo],
    },
    {
      id: 'p2-13',
      columnId: 'p1',
      repository: 'platform',
      reference: '#23204',
      title: 'Autofix path instructions, try 2',
      reason: 'Review has been waiting and may need coordination.',
      priority: 'P1',
      tags: [
        'New changes since last review',
        'Needs human review',
        'Low risk',
        'Quick review',
        'Medium complexity',
        'Low effort',
      ],
      stack: 'Change Stack',
      author: '@mateosilva (Mateo Silva)',
      overflow: '+1',
      reviewerPopover: reviewerScenarios.assignedPair,
      avatars: [fictionalAvatars.aarav, fictionalAvatars.amara, fictionalAvatars.kwame],
    },
    {
      id: 'p2-15',
      columnId: 'p1',
      repository: 'docs',
      reference: '#1369',
      title: 'Document repository tabs for security scan results',
      reason: 'Assign a reviewer to keep this moving.',
      priority: 'P1',
      tags: ['Needs human review', 'Low risk', 'Quick review', 'Low complexity', 'Low effort', 'Issue severity: Low'],
      stack: 'Change Stack',
      author: '@coderabbitai[bot]',
    },
    {
      id: 'p2-16',
      columnId: 'p1',
      repository: 'docs',
      reference: '#1281',
      title: 'Clarify reusable Agent connections',
      reason: 'Assign a reviewer to keep this moving.',
      priority: 'P1',
      tags: ['Needs human review', 'Low risk', 'Quick review', 'Low complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@coderabbitai[bot]',
    },
    {
      id: 'p2-17',
      columnId: 'p1',
      repository: 'docs',
      reference: '#1283',
      title: 'Document PR security architecture reviews',
      reason: 'Assign a reviewer to keep this moving.',
      priority: 'P1',
      tags: ['Needs human review', 'Low risk', 'Standard review', 'Low complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@coderabbitai[bot]',
    },
    {
      id: 'p2-18',
      columnId: 'p1',
      repository: 'docs',
      reference: '#1237',
      title: 'Document chat support for managed triggers',
      reason: 'This may need maintainer follow-up.',
      priority: 'P1',
      tags: ['Needs author action', 'Low risk', 'Standard review', 'Low complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@coderabbitai[bot]',
    },
    {
      id: 'p2-19',
      columnId: 'p1',
      repository: 'platform',
      reference: '#22972',
      title: 'Add metered billing period support and caching',
      reason: 'This may need maintainer follow-up.',
      priority: 'P1',
      tags: ['Needs author action', 'Low risk', 'Quick review', 'High complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@minjunpark (Min-jun Park)',
      reviewerPopover: reviewerScenarios.soloReviewer,
      avatars: [fictionalAvatars.aarav],
    },
    {
      id: 'p2-20',
      columnId: 'p1',
      repository: 'platform',
      reference: '#23718',
      title: 'Update worker configuration across services',
      reason: 'This may need maintainer follow-up.',
      priority: 'P1',
      tags: ['Needs author action', 'Low risk', 'Quick review', 'High complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@thandindlovu (Thandi Ndlovu)',
    },
    {
      id: 'p3-21',
      columnId: 'p2',
      repository: 'platform',
      reference: '#23447',
      title: 'fix(roles): scope Assigned users count to the session org [APPCONS-399]',
      reason: 'Reviewer assigned; waiting for review.',
      priority: 'P2',
      tags: [
        'New changes since last review',
        'Needs human review',
        'Low risk',
        'Quick review',
        'High complexity',
        'Low effort',
      ],
      stack: 'Change Stack',
      author: '@priyaraman (Priya Raman)',
      reviewerPopover: reviewerScenarios.assignedPair,
      avatars: [fictionalAvatars.amara],
    },
    {
      id: 'p3-22',
      columnId: 'p2',
      repository: 'platform',
      reference: '#23373',
      title: 'feat(reviews): add in-app details and card action prototype',
      reason: 'Another role owns the next action.',
      priority: 'P2',
      tags: ['Needs human review', 'Low risk', 'Quick review', 'High complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@luciatorres (Lucía Torres)',
      reviewerPopover: reviewerScenarios.suggestedCandidate,
      avatars: [fictionalAvatars.casey, fictionalAvatars.mateo],
    },
    {
      id: 'p3-23',
      columnId: 'p2',
      repository: 'platform',
      reference: '#24917',
      title: 'Verify: security full-scan lifecycle',
      reason: 'Reviewer assigned; waiting for review.',
      priority: 'P2',
      tags: [
        'New changes since last review',
        'Needs human review',
        'Low risk',
        'Quick review',
        'High complexity',
        'Low effort',
      ],
      stack: 'Change Stack',
      author: '@noorrahman (Noor Rahman)',
      reviewerPopover: reviewerScenarios.soloReviewer,
      avatars: [fictionalAvatars.kwame],
    },
    {
      id: 'p3-24',
      columnId: 'p2',
      repository: 'platform',
      reference: '#23423',
      title: 'fix(agent-runtime): validate routing config before task start',
      reason: 'Reviewer assigned; waiting for review.',
      priority: 'P2',
      tags: ['Needs human review', 'Low risk', 'Quick review', 'Medium complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@elenarossi (Elena Rossi)',
      reviewerPopover: reviewerScenarios.soloReviewer,
      avatars: [fictionalAvatars.mateo],
    },
    {
      id: 'p3-25',
      columnId: 'p2',
      repository: 'platform',
      reference: '#24778',
      title: 'fix(sandboxer): mount analysis runtime under writable jail path',
      reason: 'Reviewer assigned; waiting for review.',
      priority: 'P2',
      tags: ['Needs human review', 'Low risk', 'Quick review', 'Low complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@coderabbitai[bot]',
      reviewerPopover: reviewerScenarios.soloReviewer,
      avatars: [fictionalAvatars.nadia],
    },
    {
      id: 'p3-26',
      columnId: 'p2',
      repository: 'platform',
      reference: '#24727',
      title: 'Mark findings fixed when their patch PR merges',
      reason: 'Reviewer assigned; waiting for review.',
      priority: 'P2',
      tags: ['Needs human review', 'Low risk', 'Quick review', 'High complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@kwamemensah (Kwame Mensah)',
      reviewerPopover: reviewerScenarios.assignedPair,
      avatars: [fictionalAvatars.aarav],
    },
    {
      id: 'p3-27',
      columnId: 'p2',
      repository: 'platform',
      reference: '#23259',
      title: 'Agent runtime: authenticate private remote hydration',
      reason: 'Another role owns the next action.',
      priority: 'P2',
      tags: ['Needs author action', 'Low risk', 'Quick review', 'High complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@elenarossi (Elena Rossi)',
      reviewerPopover: reviewerScenarios.soloReviewer,
      avatars: [fictionalAvatars.amara],
    },
    {
      id: 'p3-28',
      columnId: 'p2',
      repository: 'platform',
      reference: '#23682',
      title: 'perf(dashboards): prune high-cost analytics scans by tenant',
      reason: 'Another role owns the next action.',
      priority: 'P2',
      tags: ['Needs author action', 'Low risk', 'Quick review', 'High complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@thandindlovu (Thandi Ndlovu)',
      reviewerPopover: reviewerScenarios.soloReviewer,
      avatars: [fictionalAvatars.casey],
    },
    {
      id: 'p3-29',
      columnId: 'p2',
      repository: 'platform',
      reference: '#23845',
      title: 'feat(auth): add service principal groundwork for shared services',
      reason: 'Another role owns the next action.',
      priority: 'P2',
      tags: ['Needs author action', 'Low risk', 'Quick review', 'Medium complexity', 'Low effort'],
      stack: 'Change Stack',
      author: '@emrekaya (Emre Kaya)',
      reviewerPopover: reviewerScenarios.soloReviewer,
      avatars: [fictionalAvatars.kwame],
    },
    {
      id: 'p3-30',
      columnId: 'p2',
      repository: 'webapp',
      reference: '#2531',
      title: 'Add chat bot code review guide',
      reason: 'Another role owns the next action.',
      priority: 'P2',
      tags: ['Low risk', 'Quick review', 'Low effort'],
      stack: 'Change Stack',
      author: '@arohaterangi (Aroha Te Rangi)',
    },
    {
      id: 'p3-31',
      columnId: 'p2',
      repository: 'webapp',
      reference: '#2526',
      title: 'Fix broken outbound links in English blog sample',
      reason: 'Another role owns the next action.',
      priority: 'P2',
      tags: ['Low risk', 'Quick review', 'Low effort'],
      stack: 'Change Stack',
      author: '@arohaterangi (Aroha Te Rangi)',
    },
    {
      id: 'p3-32',
      columnId: 'p2',
      repository: 'webapp',
      reference: '#2572',
      title: 'content(blog): add post-merge actions article',
      reason: 'Another role owns the next action.',
      priority: 'P2',
      tags: ['Low risk', 'Quick review', 'Low effort'],
      stack: 'Change Stack',
      author: '@arohaterangi (Aroha Te Rangi)',
    },
    {
      id: 'p4-33',
      columnId: 'p3',
      repository: 'webapp',
      reference: '#25494',
      title: 'style(marketing): align empty-state copy spacing',
      reason: 'Agent-generated CSS-only change. Check the layout before merging.',
      priority: 'P3',
      tags: ['Agent-created', 'Safe to merge', 'Low risk', 'Quick review', 'Low effort'],
      stack: 'Change Stack',
      author: '@ui-polish-agent[bot]',
    },
  ],
};

/** Reviewer details own avatar identity; cards without reviewers get the add-reviewer affordance. */
export const triageBoard: TriageBoardData = {
  ...baseTriageBoard,
  viewGroups: baseTriageBoard.viewGroups.map(group => ({
    ...group,
    views: group.views.map(view => ({
      ...view,
      count: String(cardsForView(baseTriageBoard.cards, view.id).length),
    })),
  })),
  columns: baseTriageBoard.columns.map(column => ({
    ...column,
    count: String(baseTriageBoard.cards.filter(card => card.columnId === column.id).length),
  })),
  cards: baseTriageBoard.cards.map(card => {
    const reviewerPopover = card.reviewerPopover ?? (card.avatars?.length ? undefined : reviewerScenarios.noReviewer);
    if (!reviewerPopover) return card;
    const avatars = reviewerPopover.reviewers.flatMap(reviewer => (reviewer.avatar ? [reviewer.avatar] : []));
    return {
      ...card,
      reviewerPopover,
      avatars: avatars.slice(0, 3),
      overflow: avatars.length > 3 ? `+${String(avatars.length - 3)}` : undefined,
    };
  }),
};
