import type {GlowLighting, GlowVignette} from './lib/glowSettings';
import type {ReviewStackUi} from './products/change-stack/source/ReviewStackEditor';
import type {TriageCardCopy, TriageUi, TriageViewId} from './products/triage/source/TriageEditor';
export type Gesture = 'Open_Palm' | 'Pointing_Up' | 'Pinch' | 'Swipe' | 'None';
export type BroadcastKind = 'presenter' | 'headline' | 'triage' | 'stack' | 'ticker' | 'bug' | 'ident';
export type ProductAssetKind = 'change-stack' | 'triage-board';
export type ProductView = 'overview' | 'layers' | 'architecture' | 'security';
export type ProductAnimation = 'walkthrough' | 'scene' | 'still';
export type ProductUiState = ReviewStackUi & {openSummaryIds: string[]};
export type BrandAssetKind = 'name-intro' | 'name-intro-wipe' | 'logo-reveal' | 'circle-wipe' | 'stack-wipe' | 'color-bar-wipe' | 'pixel-glow-wipe' | 'type-reveal' | 'brand-signoff' | 'signal-loop' | 'color-bar-reveal' | 'color-bar-loop' | 'color-bar-transition' | ProductAssetKind;
export type OverlayKind = 'code' | 'diagram' | 'callout' | 'terminal' | 'agentflow' | 'hero' | BroadcastKind | BrandAssetKind;
export type AssetType = 'linear' | 'looping';
export type Binding = 'cue' | 'progress' | 'follow';
export type Placement = 'left' | 'right' | 'center';
export type Sample = {t: number; x: number; y: number; pinch: number; confidence: number; gesture: Gesture; visible: boolean};
export type Cue = {id: string; time: number; gesture: Gesture};
export type Overlay = {
  id: string; kind: OverlayKind; enabled: boolean; title: string; body: string;
  start: number; duration: number; binding: Binding; placement: Placement; accent: string; scale: number;
  kicker?: string;
  company?: string; textColor?: string; detailBackground?: string; detailTextColor?: string;
  loopDuration?: number; intensity?: number; opacity?: number;
  lighting?: Partial<GlowLighting>; vignette?: Partial<GlowVignette>;
  colorway?: 'dark' | 'light'; direction?: 'left' | 'right';
  barHeight?: number; barPosition?: 'top' | 'center' | 'bottom'; barColors?: string[];
  pixelSize?: number; scatter?: number;
  productView?: ProductView; productRepository?: string; productLayer?: number;
  productAnimation?: ProductAnimation; productUi?: Partial<ProductUiState>;
  productPr?: string; productOverviewTitle?: string; productHideContext?: boolean;
  triageView?: TriageViewId; triageUi?: Partial<TriageUi>;
  triageCards?: Record<string, Partial<TriageCardCopy>>;
};
export type Project = {
  name: string; mediaUrl: string | null; mediaName: string; duration: number; fps: number;
  width: number; height: number; samples: Sample[]; cues: Cue[]; overlays: Overlay[];
  sampleMode: boolean; showTracking: boolean; mute: boolean;
  broadcast?: boolean;
  brandAsset?: boolean;
};
export type ProductEditHandler = (id: string, patch: Partial<Overlay>) => void;
export type SceneProps = {project: Project; transparent?: boolean; onProductEdit?: ProductEditHandler; reduceMotion?: boolean};
export const gestureLabel: Record<Gesture, string> = {Open_Palm: 'Open palm', Pointing_Up: 'Point', Pinch: 'Pinch', Swipe: 'Hand sweep', None: 'No gesture'};
